from typing import Any, Dict

from strands import tool

from src.clients import CLIENT


METADATA: Dict[str, Any] = {
    "resource": "accounts.origins",
    "operation": "write",
    "tags": [],
    "http_method": "delete",
    "http_path": "/v1/accounts/origins/{id}",
    "operation_id": "delete-origin",
}


async def delete_accounts_origins(
    *,
    id: str,
) -> Any:
    """
    Permanently remove an origin by ID.
    """
    return await CLIENT.accounts.origins.delete(id)


@tool(
    name="delete_accounts_origins",
    description="**Note:** This API is currently in beta.  \nPermanently removes the origin identified by `id`. If the origin is in use by any URL‑endpoints, the API will return an error.\n",
    inputSchema={
        "json": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "description": "Unique identifier for the origin. This is generated by ImageKit when you create a new origin.",
                },
            },
            "required": ["id"],
        }
    },
)
async def delete_accounts_origins_tool(
    id: str,
) -> Any:
    """
    Permanently remove an origin by ID.
    """
    return await delete_accounts_origins(id=id)
