from typing import Any, Dict

from strands import tool

from src.clients import CLIENT


METADATA: Dict[str, Any] = {
    "resource": "accounts.origins",
    "operation": "read",
    "tags": [],
    "http_method": "get",
    "http_path": "/v1/accounts/origins/{id}",
    "operation_id": "get-origin",
}


async def get_accounts_origins(
    *,
    id: str,
) -> Any:
    """
    Retrieve an origin by ID.
    """
    return await CLIENT.accounts.origins.get(id)


@tool(
    name="get_accounts_origins",
    description="**Note:** This API is currently in beta.  \nRetrieves the origin identified by `id`.\n",
    inputSchema={
        "json": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "description": "Unique identifier for the origin. This is generated by ImageKit when you create a new origin.",
                },
            },
            "required": ["id"],
        }
    },
)
async def get_accounts_origins_tool(
    id: str,
) -> Any:
    """
    Retrieve an origin by ID.
    """
    return await get_accounts_origins(id=id)
