from __future__ import annotations

from typing import Any, Dict, Optional

from strands import tool

from src.clients import CLIENT


METADATA: Dict[str, Any] = {
    "resource": "accounts.origins",
    "operation": "write",
    "tags": [],
    "http_method": "put",
    "http_path": "/v1/accounts/origins/{id}",
    "operation_id": "update-origin",
}


async def update_accounts_origins(
    *,
    id: str,
    type: Optional[str] = None,
    name: Optional[str] = None,
    access_key: Optional[str] = None,
    account_name: Optional[str] = None,
    base_url: Optional[str] = None,
    base_url_for_canonical_header: Optional[str] = None,
    bucket: Optional[str] = None,
    client_email: Optional[str] = None,
    client_id: Optional[str] = None,
    client_secret: Optional[str] = None,
    container: Optional[str] = None,
    endpoint: Optional[str] = None,
    forward_host_header_to_origin: Optional[bool] = None,
    include_canonical_header: Optional[bool] = None,
    password: Optional[str] = None,
    prefix: Optional[str] = None,
    private_key: Optional[str] = None,
    s3_force_path_style: Optional[bool] = None,
    sas_token: Optional[str] = None,
    secret_key: Optional[str] = None,
    username: Optional[str] = None,
) -> Any:
    """
    Update an origin by ID (beta).
    """
    body = {
        "type": type,
        "name": name,
        "access_key": access_key,
        "account_name": account_name,
        "base_url": base_url,
        "base_url_for_canonical_header": base_url_for_canonical_header,
        "bucket": bucket,
        "client_email": client_email,
        "client_id": client_id,
        "client_secret": client_secret,
        "container": container,
        "endpoint": endpoint,
        "forward_host_header_to_origin": forward_host_header_to_origin,
        "include_canonical_header": include_canonical_header,
        "password": password,
        "prefix": prefix,
        "private_key": private_key,
        "s3_force_path_style": s3_force_path_style,
        "sas_token": sas_token,
        "secret_key": secret_key,
        "username": username,
    }
    filtered_body = {k: v for k, v in body.items() if v is not None}

    return await CLIENT.accounts.origins.update(id, **filtered_body)


@tool(
    name="update_accounts_origins",
    description="**Note:** This API is currently in beta.  \nUpdates the origin identified by `id` and returns the updated origin object.\n",
    inputSchema={
        "json": {
            "type": "object",
            "anyOf": [
                {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string",
                            "description": "Unique identifier for the origin. This is generated by ImageKit when you create a new origin.",
                        },
                        "accessKey": {
                            "type": "string",
                            "description": "Access key for the bucket.",
                        },
                        "bucket": {
                            "type": "string",
                            "description": "S3 bucket name.",
                        },
                        "name": {
                            "type": "string",
                            "description": "Display name of the origin.",
                        },
                        "secretKey": {
                            "type": "string",
                            "description": "Secret key for the bucket.",
                        },
                        "type": {
                            "type": "string",
                            "enum": ["S3"],
                        },
                        "baseUrlForCanonicalHeader": {
                            "type": "string",
                            "description": "URL used in the Canonical header (if enabled).",
                        },
                        "includeCanonicalHeader": {
                            "type": "boolean",
                            "description": "Whether to send a Canonical header.",
                        },
                        "prefix": {
                            "type": "string",
                            "description": "Path prefix inside the bucket.",
                        },
                    },
                    "required": [
                        "id",
                        "accessKey",
                        "bucket",
                        "name",
                        "secretKey",
                        "type",
                    ],
                },
                {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string",
                            "description": "Unique identifier for the origin. This is generated by ImageKit when you create a new origin.",
                        },
                        "accessKey": {
                            "type": "string",
                            "description": "Access key for the bucket.",
                        },
                        "bucket": {
                            "type": "string",
                            "description": "S3 bucket name.",
                        },
                        "endpoint": {
                            "type": "string",
                            "description": "Custom S3-compatible endpoint.",
                        },
                        "name": {
                            "type": "string",
                            "description": "Display name of the origin.",
                        },
                        "secretKey": {
                            "type": "string",
                            "description": "Secret key for the bucket.",
                        },
                        "type": {
                            "type": "string",
                            "enum": ["S3_COMPATIBLE"],
                        },
                        "baseUrlForCanonicalHeader": {
                            "type": "string",
                            "description": "URL used in the Canonical header (if enabled).",
                        },
                        "includeCanonicalHeader": {
                            "type": "boolean",
                            "description": "Whether to send a Canonical header.",
                        },
                        "prefix": {
                            "type": "string",
                            "description": "Path prefix inside the bucket.",
                        },
                        "s3ForcePathStyle": {
                            "type": "boolean",
                            "description": "Use path-style S3 URLs?",
                        },
                    },
                    "required": [
                        "id",
                        "accessKey",
                        "bucket",
                        "endpoint",
                        "name",
                        "secretKey",
                        "type",
                    ],
                },
                {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string",
                            "description": "Unique identifier for the origin. This is generated by ImageKit when you create a new origin.",
                        },
                        "accessKey": {
                            "type": "string",
                            "description": "Access key for the bucket.",
                        },
                        "bucket": {
                            "type": "string",
                            "description": "S3 bucket name.",
                        },
                        "name": {
                            "type": "string",
                            "description": "Display name of the origin.",
                        },
                        "secretKey": {
                            "type": "string",
                            "description": "Secret key for the bucket.",
                        },
                        "type": {
                            "type": "string",
                            "enum": ["CLOUDINARY_BACKUP"],
                        },
                        "baseUrlForCanonicalHeader": {
                            "type": "string",
                            "description": "URL used in the Canonical header (if enabled).",
                        },
                        "includeCanonicalHeader": {
                            "type": "boolean",
                            "description": "Whether to send a Canonical header.",
                        },
                        "prefix": {
                            "type": "string",
                            "description": "Path prefix inside the bucket.",
                        },
                    },
                    "required": [
                        "id",
                        "accessKey",
                        "bucket",
                        "name",
                        "secretKey",
                        "type",
                    ],
                },
                {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string",
                            "description": "Unique identifier for the origin. This is generated by ImageKit when you create a new origin.",
                        },
                        "baseUrl": {
                            "type": "string",
                            "description": "Root URL for the web folder origin.",
                        },
                        "name": {
                            "type": "string",
                            "description": "Display name of the origin.",
                        },
                        "type": {
                            "type": "string",
                            "enum": ["WEB_FOLDER"],
                        },
                        "baseUrlForCanonicalHeader": {
                            "type": "string",
                            "description": "URL used in the Canonical header (if enabled).",
                        },
                        "forwardHostHeaderToOrigin": {
                            "type": "boolean",
                            "description": "Forward the Host header to origin?",
                        },
                        "includeCanonicalHeader": {
                            "type": "boolean",
                            "description": "Whether to send a Canonical header.",
                        },
                    },
                    "required": ["id", "baseUrl", "name", "type"],
                },
                {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string",
                            "description": "Unique identifier for the origin. This is generated by ImageKit when you create a new origin.",
                        },
                        "name": {
                            "type": "string",
                            "description": "Display name of the origin.",
                        },
                        "type": {
                            "type": "string",
                            "enum": ["WEB_PROXY"],
                        },
                        "baseUrlForCanonicalHeader": {
                            "type": "string",
                            "description": "URL used in the Canonical header (if enabled).",
                        },
                        "includeCanonicalHeader": {
                            "type": "boolean",
                            "description": "Whether to send a Canonical header.",
                        },
                    },
                    "required": ["id", "name", "type"],
                },
                {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string",
                            "description": "Unique identifier for the origin. This is generated by ImageKit when you create a new origin.",
                        },
                        "bucket": {
                            "type": "string",
                        },
                        "clientEmail": {
                            "type": "string",
                        },
                        "name": {
                            "type": "string",
                            "description": "Display name of the origin.",
                        },
                        "privateKey": {
                            "type": "string",
                        },
                        "type": {
                            "type": "string",
                            "enum": ["GCS"],
                        },
                        "baseUrlForCanonicalHeader": {
                            "type": "string",
                            "description": "URL used in the Canonical header (if enabled).",
                        },
                        "includeCanonicalHeader": {
                            "type": "boolean",
                            "description": "Whether to send a Canonical header.",
                        },
                        "prefix": {
                            "type": "string",
                        },
                    },
                    "required": [
                        "id",
                        "bucket",
                        "clientEmail",
                        "name",
                        "privateKey",
                        "type",
                    ],
                },
                {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string",
                            "description": "Unique identifier for the origin. This is generated by ImageKit when you create a new origin.",
                        },
                        "accountName": {
                            "type": "string",
                        },
                        "container": {
                            "type": "string",
                        },
                        "name": {
                            "type": "string",
                            "description": "Display name of the origin.",
                        },
                        "sasToken": {
                            "type": "string",
                        },
                        "type": {
                            "type": "string",
                            "enum": ["AZURE_BLOB"],
                        },
                        "baseUrlForCanonicalHeader": {
                            "type": "string",
                            "description": "URL used in the Canonical header (if enabled).",
                        },
                        "includeCanonicalHeader": {
                            "type": "boolean",
                            "description": "Whether to send a Canonical header.",
                        },
                        "prefix": {
                            "type": "string",
                        },
                    },
                    "required": [
                        "id",
                        "accountName",
                        "container",
                        "name",
                        "sasToken",
                        "type",
                    ],
                },
                {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string",
                            "description": "Unique identifier for the origin. This is generated by ImageKit when you create a new origin.",
                        },
                        "baseUrl": {
                            "type": "string",
                            "description": "Akeneo instance base URL.",
                        },
                        "clientId": {
                            "type": "string",
                            "description": "Akeneo API client ID.",
                        },
                        "clientSecret": {
                            "type": "string",
                            "description": "Akeneo API client secret.",
                        },
                        "name": {
                            "type": "string",
                            "description": "Display name of the origin.",
                        },
                        "password": {
                            "type": "string",
                            "description": "Akeneo API password.",
                        },
                        "type": {
                            "type": "string",
                            "enum": ["AKENEO_PIM"],
                        },
                        "username": {
                            "type": "string",
                            "description": "Akeneo API username.",
                        },
                        "baseUrlForCanonicalHeader": {
                            "type": "string",
                            "description": "URL used in the Canonical header (if enabled).",
                        },
                        "includeCanonicalHeader": {
                            "type": "boolean",
                            "description": "Whether to send a Canonical header.",
                        },
                    },
                    "required": [
                        "id",
                        "baseUrl",
                        "clientId",
                        "clientSecret",
                        "name",
                        "password",
                        "type",
                        "username",
                    ],
                },
            ],
        }
    },
)
async def update_accounts_origins_tool(
    id: str,
    type: Optional[str] = None,
    name: Optional[str] = None,
    access_key: Optional[str] = None,
    account_name: Optional[str] = None,
    base_url: Optional[str] = None,
    base_url_for_canonical_header: Optional[str] = None,
    bucket: Optional[str] = None,
    client_email: Optional[str] = None,
    client_id: Optional[str] = None,
    client_secret: Optional[str] = None,
    container: Optional[str] = None,
    endpoint: Optional[str] = None,
    forward_host_header_to_origin: Optional[bool] = None,
    include_canonical_header: Optional[bool] = None,
    password: Optional[str] = None,
    prefix: Optional[str] = None,
    private_key: Optional[str] = None,
    s3_force_path_style: Optional[bool] = None,
    sas_token: Optional[str] = None,
    secret_key: Optional[str] = None,
    username: Optional[str] = None,
) -> Any:
    """
    Update an origin by ID (beta).
    """
    return await update_accounts_origins(
        id=id,
        type=type,
        name=name,
        access_key=access_key,
        account_name=account_name,
        base_url=base_url,
        base_url_for_canonical_header=base_url_for_canonical_header,
        bucket=bucket,
        client_email=client_email,
        client_id=client_id,
        client_secret=client_secret,
        container=container,
        endpoint=endpoint,
        forward_host_header_to_origin=forward_host_header_to_origin,
        include_canonical_header=include_canonical_header,
        password=password,
        prefix=prefix,
        private_key=private_key,
        s3_force_path_style=s3_force_path_style,
        sas_token=sas_token,
        secret_key=secret_key,
        username=username,
    )
