from typing import Any, Dict

from strands import tool

from src.clients import CLIENT


METADATA: Dict[str, Any] = {
    "resource": "accounts.urlEndpoints",
    "operation": "write",
    "tags": [],
    "http_method": "delete",
    "http_path": "/v1/accounts/url-endpoints/{id}",
    "operation_id": "delete-url-endpoint",
}


async def delete_accounts_url_endpoints(
    *,
    id: str,
) -> Any:
    """
    Delete a URL endpoint by ID (beta).
    """
    return await CLIENT.accounts.url_endpoints.delete(id)


@tool(
    name="delete_accounts_url_endpoints",
    description="**Note:** This API is currently in beta.  \nDeletes the URL‑endpoint identified by `id`. You cannot delete the default URL‑endpoint created by ImageKit during account creation.\n",
    inputSchema={
        "json": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "description": "Unique identifier for the URL-endpoint. This is generated by ImageKit when you create a new URL-endpoint. For the default URL-endpoint, this is always `default`.",
                },
            },
            "required": ["id"],
        }
    },
)
async def delete_accounts_url_endpoints_tool(
    id: str,
) -> Any:
    """
    Delete a URL endpoint by ID (beta).
    """
    return await delete_accounts_url_endpoints(id=id)
