from __future__ import annotations

from typing import Any, Dict, List, Optional

from strands import tool

from src.clients import CLIENT
from src.utils import maybe_filter


METADATA: Dict[str, Any] = {
    "resource": "accounts.urlEndpoints",
    "operation": "read",
    "tags": [],
    "http_method": "get",
    "http_path": "/v1/accounts/url-endpoints",
    "operation_id": "list-url-endpoints",
}


def _serialize_url_endpoint(endpoint: Any) -> Dict[str, Any]:
    """
    Normalize SDK URL endpoint objects into plain dicts.
    """
    if hasattr(endpoint, "model_dump"):
        return endpoint.model_dump()
    if hasattr(endpoint, "dict"):
        return endpoint.dict()
    return dict(endpoint)


async def list_accounts_url_endpoints(
    *,
    filter_spec: Optional[Any] = None,
) -> List[Dict[str, Any]]:
    """
    List all URL endpoints configured for the current account (beta).

    - Use `filter_spec` (glom spec) to shrink the response payload.
    """
    raw = await CLIENT.accounts.url_endpoints.list()
    response = [_serialize_url_endpoint(endpoint) for endpoint in raw]
    return maybe_filter(filter_spec, response)


@tool(
    name="list_accounts_url_endpoints",
    description="When using this tool, always use the `filter_spec` parameter to reduce the response size and improve performance.\n\nOnly omit if you're sure you don't need the data.\n\n**Note:** This API is currently in beta.  \nReturns an array of all URL‑endpoints configured including the default URL-endpoint generated by ImageKit during account creation.\n\n\n# Response Schema\n```json\n{\n  type: 'array',\n  items: {\n    $ref: '#/$defs/url_endpoint_response'\n  },\n  $defs: {\n    url_endpoint_response: {\n      type: 'object',\n      title: 'URL‑endpoint Response',\n      description: 'URL‑endpoint object as returned by the API.',\n      properties: {\n        id: {\n          type: 'string',\n          description: 'Unique identifier for the URL-endpoint. This is generated by ImageKit when you create a new URL-endpoint. For the default URL-endpoint, this is always `default`.'\n        },\n        description: {\n          type: 'string',\n          description: 'Description of the URL endpoint.'\n        },\n        origins: {\n          type: 'array',\n          description: 'Ordered list of origin IDs to try when the file isn’t in the Media Library; ImageKit checks them in the sequence provided. Origin must be created before it can be used in a URL endpoint.',\n          items: {\n            type: 'string',\n            description: 'Unique identifier for the origin. This is generated by ImageKit when you create a new origin.'\n          }\n        },\n        urlPrefix: {\n          type: 'string',\n          description: 'Path segment appended to your base URL to form the endpoint (letters, digits, and hyphens only — or empty for the default endpoint).'\n        },\n        urlRewriter: {\n          anyOf: [            {\n              type: 'object',\n              title: 'Cloudinary URL Rewriter',\n              properties: {\n                preserveAssetDeliveryTypes: {\n                  type: 'boolean',\n                  description: 'Whether to preserve `<asset_type>/<delivery_type>` in the rewritten URL.'\n                },\n                type: {\n                  type: 'string',\n                  enum: [                    'CLOUDINARY'\n                  ]\n                }\n              },\n              required: [                'preserveAssetDeliveryTypes',\n                'type'\n              ]\n            },\n            {\n              type: 'object',\n              title: 'Imgix URL Rewriter',\n              properties: {\n                type: {\n                  type: 'string',\n                  enum: [                    'IMGIX'\n                  ]\n                }\n              },\n              required: [                'type'\n              ]\n            },\n            {\n              type: 'object',\n              title: 'Akamai URL Rewriter',\n              properties: {\n                type: {\n                  type: 'string',\n                  enum: [                    'AKAMAI'\n                  ]\n                }\n              },\n              required: [                'type'\n              ]\n            }\n          ],\n          description: 'Configuration for third-party URL rewriting.'\n        }\n      },\n      required: [        'id',\n        'description',\n        'origins',\n        'urlPrefix'\n      ]\n    }\n  }\n}\n```",
    inputSchema={
        "json": {
            "type": "object",
            "properties": {
                "filter_spec": {
                    "type": "string",
                    "title": "filter_spec",
                    "description": 'A filter_spec to apply to the response to include certain fields. Consult the output schema in the tool description to see the fields that are available.\n\nFor example: to include only the `name` field in every object of a results array, you can provide ".results[].name".\n\nFor more information, see the [jq documentation](https://jqlang.org/manual/).',
                },
            },
            "required": [],
        }
    },
)
async def list_accounts_url_endpoints_tool(
    filter_spec: Optional[Any] = None,
) -> List[Dict[str, Any]]:
    """
    List all URL endpoints configured for the current account (beta).

    Prefer `filter_spec` to reduce response size when possible.
    """
    return await list_accounts_url_endpoints(filter_spec=filter_spec)
