from typing import Any, Dict, Optional, Sequence

from strands import tool

from src.clients import CLIENT
from src.utils.utils import maybe_filter


METADATA: Dict[str, Any] = {
    "resource": "accounts.urlEndpoints",
    "operation": "write",
    "tags": [],
    "http_method": "put",
    "http_path": "/v1/accounts/url-endpoints/{id}",
    "operation_id": "update-url-endpoint",
}


def _serialize_url_endpoint(result: Any) -> Dict[str, Any]:
    """
    Normalize SDK responses into plain dicts.
    """
    if hasattr(result, "model_dump"):
        return result.model_dump()
    if hasattr(result, "dict"):
        return result.dict()
    return dict(result)


async def update_accounts_url_endpoints(
    *,
    id: str,
    description: str,
    origins: Optional[Sequence[str]] = None,
    url_prefix: Optional[str] = None,
    url_rewriter: Optional[Dict[str, Any]] = None,
    filter_spec: Optional[Any] = None,
) -> Dict[str, Any]:
    """
    Update a URL endpoint (beta).

    - Use `filter_spec` (glom spec) to shrink the response payload.
    """
    body = {
        "description": description,
        "origins": origins,
        "url_prefix": url_prefix,
        "url_rewriter": url_rewriter,
    }
    filtered_body = {k: v for k, v in body.items() if v is not None}

    raw = await CLIENT.accounts.url_endpoints.update(id, **filtered_body)
    response = _serialize_url_endpoint(raw)
    return maybe_filter(filter_spec, response)


@tool(
    name="update_accounts_url_endpoints",
    description="When using this tool, always use the `glom spec` parameter to reduce the response size and improve performance.\n\nOnly omit if you're sure you don't need the data.\n\n**Note:** This API is currently in beta.  \nUpdates the URL‑endpoint identified by `id` and returns the updated object.\n\n\n# Response Schema\n```json\n{\n  $ref: '#/$defs/url_endpoint_response',\n  $defs: {\n    url_endpoint_response: {\n      type: 'object',\n      title: 'URL‑endpoint Response',\n      description: 'URL‑endpoint object as returned by the API.',\n      properties: {\n        id: {\n          type: 'string',\n          description: 'Unique identifier for the URL-endpoint. This is generated by ImageKit when you create a new URL-endpoint. For the default URL-endpoint, this is always `default`.'\n        },\n        description: {\n          type: 'string',\n          description: 'Description of the URL endpoint.'\n        },\n        origins: {\n          type: 'array',\n          description: 'Ordered list of origin IDs to try when the file isn’t in the Media Library; ImageKit checks them in the sequence provided. Origin must be created before it can be used in a URL endpoint.',\n          items: {\n            type: 'string',\n            description: 'Unique identifier for the origin. This is generated by ImageKit when you create a new origin.'\n          }\n        },\n        urlPrefix: {\n          type: 'string',\n          description: 'Path segment appended to your base URL to form the endpoint (letters, digits, and hyphens only — or empty for the default endpoint).'\n        },\n        urlRewriter: {\n          anyOf: [            {\n              type: 'object',\n              title: 'Cloudinary URL Rewriter',\n              properties: {\n                preserveAssetDeliveryTypes: {\n                  type: 'boolean',\n                  description: 'Whether to preserve `<asset_type>/<delivery_type>` in the rewritten URL.'\n                },\n                type: {\n                  type: 'string',\n                  enum: [                    'CLOUDINARY'\n                  ]\n                }\n              },\n              required: [                'preserveAssetDeliveryTypes',\n                'type'\n              ]\n            },\n            {\n              type: 'object',\n              title: 'Imgix URL Rewriter',\n              properties: {\n                type: {\n                  type: 'string',\n                  enum: [                    'IMGIX'\n                  ]\n                }\n              },\n              required: [                'type'\n              ]\n            },\n            {\n              type: 'object',\n              title: 'Akamai URL Rewriter',\n              properties: {\n                type: {\n                  type: 'string',\n                  enum: [                    'AKAMAI'\n                  ]\n                }\n              },\n              required: [                'type'\n              ]\n            }\n          ],\n          description: 'Configuration for third-party URL rewriting.'\n        }\n      },\n      required: [        'id',\n        'description',\n        'origins',\n        'urlPrefix'\n      ]\n    }\n  }\n}\n```",
    inputSchema={
        "json": {
            "properties": {
                "description": {
                    "description": "Description of the URL endpoint.",
                    "type": "string",
                },
                "id": {
                    "description": "Unique identifier for the URL-endpoint. This is "
                    "generated by ImageKit when you create a new "
                    "URL-endpoint. For the default URL-endpoint, this "
                    "is always `default`.",
                    "type": "string",
                },
                "filter_spec": {
                    "description": "A glom spec to apply to the response to "
                    "include certain fields. Consult the output "
                    "schema in the tool description to see the "
                    "fields that are available.\n"
                    "\n"
                    "For example: to include only the `name` "
                    "field in every object of a results array, "
                    'you can provide ".results[].name".\n'
                    "\n"
                    "For more information, see the [glom"
                    "documentation](http://glom.readthedocs.io/).",
                    "title": "glom spec",
                    "type": "string",
                },
                "origins": {
                    "description": "Ordered list of origin IDs to try when the "
                    "file isn’t in the Media Library; ImageKit "
                    "checks them in the sequence provided. Origin "
                    "must be created before it can be used in a "
                    "URL endpoint.",
                    "items": {
                        "description": "Unique identifier for the origin. "
                        "This is generated by ImageKit when "
                        "you create a new origin.",
                        "type": "string",
                    },
                    "type": "array",
                },
                "url_prefix": {
                    "description": "Path segment appended to your base URL to "
                    "form the endpoint (letters, digits, and "
                    "hyphens only — or empty for the default "
                    "endpoint).",
                    "type": "string",
                },
                "url_rewriter": {
                    "anyOf": [
                        {
                            "properties": {
                                "preserve_asset_delivery_types": {
                                    "description": "Whether "
                                    "to "
                                    "preserve "
                                    "`<asset_type>/<delivery_type>` "
                                    "in "
                                    "the "
                                    "rewritten "
                                    "URL.",
                                    "type": "boolean",
                                },
                                "type": {"enum": ["CLOUDINARY"], "type": "string"},
                            },
                            "required": ["type"],
                            "title": "Cloudinary URL Rewriter",
                            "type": "object",
                        },
                        {
                            "properties": {
                                "type": {"enum": ["IMGIX"], "type": "string"}
                            },
                            "required": ["type"],
                            "title": "Imgix URL Rewriter",
                            "type": "object",
                        },
                        {
                            "properties": {
                                "type": {"enum": ["AKAMAI"], "type": "string"}
                            },
                            "required": ["type"],
                            "title": "Akamai URL Rewriter",
                            "type": "object",
                        },
                    ],
                    "description": "Configuration for third-party URL rewriting.",
                },
            },
            "required": ["id", "description"],
            "type": "object",
        }
    },
)
async def update_accounts_url_endpoints_tool(
    id: str,
    description: str,
    origins: Optional[Sequence[str]] = None,
    url_prefix: Optional[str] = None,
    url_rewriter: Optional[Dict[str, Any]] = None,
    filter_spec: Optional[Any] = None,
) -> Dict[str, Any]:
    """
    Update a URL endpoint (beta).

    Prefer `filter_spec` to reduce response size when possible.
    """
    return await update_accounts_url_endpoints(
        id=id,
        description=description,
        origins=origins,
        url_prefix=url_prefix,
        url_rewriter=url_rewriter,
        filter_spec=filter_spec,
    )
